[package]
name = "rustmtca"
version = "0.1.0"
edition = "2018"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.5", default-features = false }

[lib]
name = "rustmtca"
crate-type = ["dylib"]

[dependencies]
